.TH "findami" "1" "November 2015" "version 0.1.0"
.SH NAME
.B findami 
\- find amazon machine images
.SH SYNOPSIS
findami [-created-by username] [-latest]
.SH DESCRIPTION
.B findami
searches for amazon machine images through Amazon's ec2 api. It will use your 
defauls aws credentials. Without any options it will return all images owned by
the account.
.SH OPTIONS
.TP
.B -created-by " username"
Filter images by the user that created it. To specify the user that created the
image add the tag "Created By" with the users name to the image
.TP
.B -latest
Find the latest image created as determined by the Creation Date.
